# Generated by Django 5.2.6 on 2025-10-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_child_gender_grandparent_gender_parent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255),
        ),
        migrations.AlterField(
            model_name='grandparent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255),
        ),
        migrations.AlterField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255),
        ),
    ]
