# Generated by Django 5.2.6 on 2025-10-02 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_child_gender_alter_grandparent_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(blank=True, choices=[('application/pdf', 'PDF Document'), ('image/jpeg', 'JPEG Image'), ('image/png', 'PNG Image'), ('text/plain', 'Plain Text'), ('text/html', 'HTML Document'), ('application/json', 'JSON Document'), ('application/xml', 'XML Document')], help_text="Mime type of the content, with charset etc. (e.g., 'text/plain; charset=UTF-8')", max_length=100, null=True)),
                ('size', models.PositiveIntegerField(blank=True, help_text='Number of bytes of content represented (in base64). Used for data attachments.', null=True)),
                ('data', models.FileField(help_text='The data of the attachment', upload_to='attachments/')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(help_text='The name of the child', max_length=255),
        ),
        migrations.AlterField(
            model_name='grandparent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='The gender of the grandparent', max_length=255),
        ),
        migrations.AlterField(
            model_name='grandparent',
            name='name',
            field=models.CharField(help_text='The name of the grandparent', max_length=255),
        ),
        migrations.AddField(
            model_name='grandparent',
            name='profile_picture',
            field=models.ForeignKey(help_text='The profile picture of the grandparent', null=True, on_delete=django.db.models.deletion.CASCADE, to='family.attachments'),
        ),
    ]
