# Generated by Django 5.2.6 on 2025-10-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_attachments_alter_child_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grandparent',
            name='profile_picture',
        ),
    ]
