# Generated by Django 5.2.6 on 2025-10-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_remove_grandparent_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='grandparent',
            new_name='grand_parent',
        ),
    ]
