# Generated by Django 5.2.6 on 2025-10-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_rename_grandparent_parent_grand_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parent',
            new_name='GrandChild',
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
        migrations.AlterModelOptions(
            name='grandchild',
            options={'verbose_name': 'Grand Child', 'verbose_name_plural': 'Grand Children'},
        ),
    ]
