# Generated by Django 5.2.6 on 2025-10-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_rename_parent_grandchild_delete_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family.grandchild'),
        ),
        migrations.AlterField(
            model_name='grandchild',
            name='grand_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_children', to='family.grandparent'),
        ),
    ]
