# Generated by Django 5.2.6 on 2025-10-19 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_child_created_by_child_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='child',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='grandchild',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grandchild',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='grandparent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grandparent',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grandchild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='grandchild',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grandparent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='grandparent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
