from config.env import env

STRAWBERRY_DJANGO = {
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
}


ENABLE_GRAPHIQL = env.bool("DJANGO_DEBUG", default=True)
